title: 「研究開発型スタートアップと事業会社のオープンイノベーション促進のためのモデル契約書ver1.0」の改訂に向けた、GitHub（ギットハブ）を用いた意見募集
description: 2020年度、経済産業省は特許庁と連携して、研究開発型スタートアップと事業会社の連携交渉する際に留意すべきポイントについて解説したモデル契約書（新素材編、AI編）を策定しました。今年度は、モデル契約書の更なる改善を目指し、以下のプロセスで改訂作業を実施します。今回の改訂プロセスでは、モデル契約書のユーザー及び現在ユーザーではない方々とも広くコミュニケーションを行い、改善に向けたフィードバックを受けることを目的として、オープンな場で不特定多数が編集に携わることが出来るシステムの1つであるGitHubを用いた意見募集をトライアル実施します。
theme: jekyll-theme-slate
